

services:

  api:
    build:
      context: ..
      dockerfile: services/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../services/api/.env
    depends_on:
      - db
    volumes:
      - ../services/api:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - ../services/api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  shadow_db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: expense_tracker_shadow
    volumes:
      - shadow_postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  shadow_postgres_data: