

services:

  api:
    build:
      context: ..
      dockerfile: services/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../services/api/.env
    depends_on:
      - db
    volumes:
      - ../services/api:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - ../services/api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: