export const defaultCategories: Array<string> = [
  'Starting Balance',
  'Deposit',
  'No Category',
  'Miscellaneous',
  'Salary',
  'Freelance',
  'Investment',
  'Rent',
  'Utilities',
  'Transportation',
  'Healthcare',
  'Entertainment',
  'Groceries',
  'Bills',
  'Subscription',
  'Hobby',
  'Gift',
  'Clothes',
  'Furniture',
  'Appliance',
  'Business',
  'Leisure',
  'Food',
  'Drinks',
];
